### ISSUE TITLE
boss- 财务审计模块

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/boss#1]
1、主体显示界面
![image](https://user-images.githubusercontent.com/27998601/42519476-b9837d72-8496-11e8-8f46-11e117bfb807.png)

2、弹窗确认界面
![default](https://user-images.githubusercontent.com/27998601/42515230-dd10cb22-848d-11e8-8b16-17eeafcc7ab6.png)
![default](https://user-images.githubusercontent.com/27998601/42518482-8176cce2-8494-11e8-9e10-6536f8e3a6a3.png)

**Comment by jcouyang** [comment]
@DXcheng 验收 👉  https://boss.51dianxiaoge.com/management/#/banking

**Comment by DXcheng** [comment]
![image](https://user-images.githubusercontent.com/27998601/42854342-00c043c8-8a6e-11e8-8276-ecffa743e8d0.png)
1、项目提交银行账户申请后BOSS界面刷新状态，审核信息显示空白状态，需重新登录再次刷新
2、审核确认界面缺少，支付宝账号名称显示

**Comment by jcouyang** [comment]
0. 脏数据删了
> 1. 项目提交银行账户申请后BOSS界面刷新状态，审核信息显示空白状态，需重新登录再次刷新
- [x] 未登录自动跳转到登陆页面
> 2. 审核确认界面缺少，支付宝账号名称显示
- [x] 显示账户名

**Comment by jcouyang** [comment]
@DXcheng 这张卡可以关了吗?
