### ISSUE TITLE
BOSS-收入页面筛选字段变更

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/boss#14]
筛选条件：
1、微信
2、支付宝
3、微信公众号
4、人工充值
备注：默认为“全部类型”
![image](https://user-images.githubusercontent.com/27998601/43840981-a65bc0b8-9b54-11e8-87d1-e3b65b67d1ed.png)

**Comment by jcouyang** [comment]
修改已部署 @DXcheng
