### ISSUE TITLE
BOSS-收入栏目，交易流水丢失

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/boss#16]
1、boss页面显示8月9日充值2笔10元交易记录，在财务审核收入界面对次2笔记录无显示。
![image](https://user-images.githubusercontent.com/27998601/43907781-dee31d9e-9c28-11e8-8732-19fceddf9204.png)
提现审核无交易记录
![image](https://user-images.githubusercontent.com/27998601/43907911-26a116d6-9c29-11e8-8bd0-f0083cc8af17.png)

**Comment by jcouyang** [comment]
修改已部署 @DXcheng
