### ISSUE TITLE
boss-顶栏增加搜索功能

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/boss#2]
1、搜索功能只对当前选中tab模块有效
2、模糊查找当前功能页面字段
比如：选中财务模块搜索项目名称、支付宝、银行卡信息等有效字段，显示搜索内容全部匹配信息。
3、除boss首页以外全部模块支持模糊搜索功能
![image](https://user-images.githubusercontent.com/27998601/42570645-2ba9b21c-8547-11e8-95e2-52192865dbd7.png)

**Comment by jcouyang** [comment]
@DXcheng 验收 👉 https://boss.51dianxiaoge.com/management/#/banking
