### ISSUE TITLE
boss-财务审核模块

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/boss#3]
![default](https://user-images.githubusercontent.com/27998601/42575569-6f120d86-8553-11e8-94ed-d096bdda0815.jpg)

**Comment by jcouyang** [comment]
@DXcheng  这交易类型能解释下吗?  这页不是提现明细审核么,其他那几个是要怎么显示?

**Comment by jcouyang** [comment]
拆成3张卡
- [X] 提现审核
- [x] filters
  - [x] 时间
  - [x] 状态
  - [x] 总金额显示
- [ ] 充值明细,缴费,服务费 (另外建卡)

**Comment by DXcheng** [comment]
支出界面功能定义：
1、搜索定义为模糊搜索字段支持：项目名称、交易账号
2、去除“全部类型”搜索栏
3、审核状态改为：审核人 显示当前操作账号
4、日历查询区段定义为任意时间

**Comment by DXcheng** [comment]
- [X] 1、更改审核页面标题栏颜色（与银行卡审核标题栏颜色保持一致）
- [X] 2、增加操作时间，也就是点击审核状态的时间。

**Comment by jcouyang** [comment]
@DXcheng 修改已部署
