### ISSUE TITLE
BOSS-登陆首页加载数据失效，自动返回登陆界面

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/boss#7]
![image](https://user-images.githubusercontent.com/27998601/43325139-8156c8f0-91e8-11e8-9020-1c2120aa0589.png)
返回登陆界面
![image](https://user-images.githubusercontent.com/27998601/43325174-99ef8fdc-91e8-11e8-8813-8cf9359673b5.png)

**Comment by jcouyang** [comment]
这有什么问题? session过期就是要重新登录的

**Comment by jcouyang** [comment]
设成30 天过期了, 勾上 remember me的话

**Comment by DXcheng** [comment]
这个首页登录字段改成中文
![default](https://user-images.githubusercontent.com/27998601/43473517-f45990fc-9522-11e8-8f1b-93e82f0bcce2.png)

**Comment by jcouyang** [comment]
@DXcheng 修改已部署
